<script lang="ts">
	import * as Accordion from '$lib/components/ui/accordion';
	import H2 from './H2.svelte';
</script>

<section>
	<H2>Frequently asked questions</H2>

	<Accordion.Root class="w-full">
		<Accordion.Item value="item-1">
			<Accordion.Trigger>What is CaptionThat?</Accordion.Trigger>
			<Accordion.Content>
				CaptionThat is a web application designed to generate captions for your posts. Simply upload
				your image, and our AI will generate a suitable caption for you.
			</Accordion.Content>
		</Accordion.Item>

		<Accordion.Item value="item-2">
			<Accordion.Trigger>Is there a cost associated with using CaptionThat?</Accordion.Trigger>
			<Accordion.Content>
				No, at the moment CaptionThat is completely free to use. We may introduce a paid tier in the
				future.
			</Accordion.Content>
		</Accordion.Item>

		<Accordion.Item value="item-3">
			<Accordion.Trigger>How do I generate captions with CaptionThat?</Accordion.Trigger>
			<Accordion.Content>
				Get started by clicking the "Try it out for free" button. Once you're on the application
				page, upload your image, and click "Generate Caption". Our AI will then present you with a
				generated caption, which you can customize to match your style or the specific nuances of
				your image.
			</Accordion.Content>
		</Accordion.Item>

		<Accordion.Item value="item-4">
			<Accordion.Trigger>What types of images can I upload to CaptionThat?</Accordion.Trigger>
			<Accordion.Content>
				CaptionThat is compatible with a variety of image formats including JPEG, PNG, WEBP, AVIF
				and GIF. We recommend using high-resolution images to ensure the captions generated by our
				AI are as relevant and accurate as possible.
			</Accordion.Content>
		</Accordion.Item>

		<Accordion.Item value="item-5">
			<Accordion.Trigger
				>What steps can I take if a generated caption isn't quite right for my image?</Accordion.Trigger
			>
			<Accordion.Content>
				If the caption doesn't seem to align with your image, consider the following options: First,
				you can adjust the 'Tone' and 'Context' fields to provide more specific guidance to the AI.
				Describing the desired mood or themes can lead to a more fitting caption. Alternatively, you
				can generate a new caption for a fresh set of ideas. Lastly, you have the option to manually
				refine any generated caption, adding your personal touch or specific details to capture the
				essence of your image perfectly.
			</Accordion.Content>
		</Accordion.Item>

		<Accordion.Item value="item-6">
			<Accordion.Trigger>How does CaptionThat handle user data and privacy?</Accordion.Trigger>
			<Accordion.Content>
				We take data privacy very seriously. Images uploaded to CaptionThat are only used to
				generate captions and are not stored on our servers.
			</Accordion.Content>
		</Accordion.Item>
	</Accordion.Root>
</section>
