<script lang="ts">
	import * as Accordion from '$lib/components/ui/accordion';
	import H2 from './H2.svelte';

	const faqs = [
		{
			question: 'What is CaptionThat?',
			answer:
				'CaptionThat is a web application designed to generate captions for your posts. Simply upload your image, and our AI will generate a suitable caption for you.'
		},
		{
			question: 'Is there a cost associated with using CaptionThat?',
			answer:
				'No, at the moment CaptionThat is completely free to use. We may introduce a paid tier in the future.'
		},
		{
			question: 'How do I generate captions with CaptionThat?',
			answer:
				"Get started by clicking the 'Try it out for free' button. Once you're on the application page, upload your image, and click 'Generate Caption'. Our AI will then present you with a generated caption, which you can customize to match your style or the specific nuances of your image."
		},
		{
			question: 'What types of images can I upload to CaptionThat?',
			answer:
				'CaptionThat is compatible with a variety of image formats including JPEG, PNG, WEBP, AVIF, and GIF. We recommend using high-resolution images to ensure the captions generated by our AI are as relevant and accurate as possible.'
		},
		{
			question: "What steps can I take if a generated caption isn't quite right for my image?",
			answer:
				"If the caption doesn't seem to align with your image, consider the following options: First, you can adjust the 'Tone' and 'Context' fields to provide more specific guidance to the AI. Describing the desired mood or themes can lead to a more fitting caption. Alternatively, you can generate a new caption for a fresh set of ideas. Lastly, you have the option to manually refine any generated caption, adding your personal touch or specific details to capture the essence of your image perfectly."
		},
		{
			question: 'How does CaptionThat handle user data and privacy?',
			answer:
				'We take data privacy very seriously. Images uploaded to CaptionThat are only used to generate captions and are not stored on our servers.'
		}
	];

	const faqSchema = {
		'@context': 'https://schema.org',
		'@type': 'FAQPage',
		mainEntity: faqs.map((faq) => ({
			'@type': 'Question',
			name: faq.question,
			acceptedAnswer: {
				'@type': 'Answer',
				text: faq.answer
			}
		}))
	};
</script>

<svelte:head>
	{@html `<script type="application/ld+json">${JSON.stringify(faqSchema)}</script>`}
</svelte:head>

<section>
	<H2>Frequently asked questions</H2>

	<Accordion.Root>
		{#each faqs as { question, answer }, i}
			<Accordion.Item value={`item-${i + 1}`}>
				<Accordion.Trigger>{question}</Accordion.Trigger>
				<Accordion.Content>
					{@html answer}
				</Accordion.Content>
			</Accordion.Item>
		{/each}
	</Accordion.Root>
</section>

<style>
	section :global(button) {
		@apply text-left;
	}
</style>
